### PR TITLE
Fix examples for Firefox >= 60 and Chrome

### PR DESCRIPTION
**Pull request by Julian0815**
The examples are not working in Firefox and Chrome.
I took a look at the js implementation of https://demo.yubico.com/u2f to fix it.
Please review!

### CODE REVIEW

**Comment by Julian0815** [comment]
Hi,
I think the u2f-lib.js should work in the old version.

**Comment by klali** [comment]
So u2f-api.js is only used in chrome, so for firefox this will work without it updated. Did you try this update in chrome?

**Comment by Julian0815** [comment]
In chromium it works only with the old lib

**Comment by klali** [comment]
This requires the new u2f-api.js to work in chrome, I'll make that update. Merging this now.

Thanks!

**Pull request merged**
