### PR TITLE
Use __DIR__ instead of getcwd()

### PR DESCRIPTION
**Pull request by LukasReschke**
getcwd() is doomed to fail as soon as the tests are executed from another folder.

Required for https://github.com/Yubico/php-u2flib-server/issues/35

### CODE REVIEW

**Comment by LukasReschke** [comment]
Generally speaking try to avoid `getcwd` :smile:

**Comment by klali** [comment]
The changes to phpunit.xml here, are they supposed to be in this commit?

**Comment by LukasReschke** [comment]
> The changes to phpunit.xml here, are they supposed to be in this commit?

Yes. There is no vendor folder here as far I can tell which causes problems with other unit testing tools that try to loop over the folder anyways.

**Comment by klali** [comment]
Ok.. That was probably added when we used composer more, probably makes sense to drop now. Merging.

**Pull request merged**
