### PR TITLE
Code cleanup, PSR-2/4, security fixes, and PHP 7 only support

### PR DESCRIPTION
**Pull request by Zae**
Hiya,

I'm not sure if you accept merge requests, but I noticed the code of this library was getting very stale, so I had some fun with the code, I changed a lot of stuff.

This continues on the work I did in #69 but in this version I dropped all support for PHP < 7

## PHP 7 fixes
+ PHP 7 version of PHPUnit
+ Added strict types
+ Added return types
+ Added parameter types

### CODE REVIEW

**Comment by Zae** [comment]
Hi @klali ,

That really depends, do you want to keep PHP 5 (#69) support or do you want to use the new (strict) typing features of PHP 7.

Also which non style/structure-features would you like to keep, I could make a new PR with only those changes.

**Comment by klali** [comment]
Ah. I believe we should have this support php 5 while that is supported as a platform (which I read to be 2018-12-31).

* The switch to random_bytes() happened in #64 
* the constant_time encoding I'm not sure if it's needed, base64 is only done on "public" values I think.
array() / [] I don't have a real opinion on
* Spliiting the classes I'm not very keen on
* Changing 'sha256' to a const is fine
* PSR-2 re-formatting I'd like to skip
* namespace for tests is fine if it makes things simpler I guess

**Comment by Zae** [comment]
Hey @klali ,

That doesn't really leave a lot then, especially if this lib is basically deprecated now.

Just wondering, does yubico have a library like this for the u2f part of webauthn?

**Comment by emlun** [comment]
Not for PHP at this time, but we do have them for [Java][java], [Python][py] and [C][c]. We're considering making one for PHP, but we haven't planned or commited to it.

[java]: https://github.com/Yubico/java-webauthn-server/
[c]: https://github.com/Yubico/libfido2/
[py]: https://github.com/Yubico/python-fido2

**Comment by Zae** [comment]
Hi @klali ,

My reasons for the changes are this:

psr-2/psr-4, big part of the community is switching or already using the psr-2 rules and a psr-4 compatible autoloader. I think this really adds to readability which is especially important in a security oriented library. 
Same for the array() vs [] change, I think it adds readability and consistency with other languages such as javascript.
Same with the const, I think it adds readability and make the code somewhat easier to change later on, if at all possible to change the hashing algo.

namespacing the tests makes it more part of the codebase itself I think, also it makes it possible to use little tricks where you override built-in functions from php to make mock versions if needed.

Constant Time Encoding I added because I'm a bit paranoid about timing attacks lately :P, but I don't really know if it's really needed in this usecase. Maybe @paragonie-scott (does this tag even work?) knows if it's really necessary here?

php 7 change, php 5 is basically already deprecated, the dec 2018 date is for security fixes only. Also you are not really blocking php 5 users from using this library if you merge the php 7 only stuff. You could tag a 2.0.0 version with the php7 only stuff and php5 users will use the 1.0.1 version. I think the stricter types are very important for a security oriented library.

Other than that, I could create a rebased version with only the const / array and test namespace changes, but it feels a bit pointless tbh.

**Comment by Spomky** [comment]
Hi all,

I fully agree with @Zae. As this topic never moved forward (e.g. https://github.com/Yubico/php-u2flib-server/pull/49 in May 2016),  I started to work on my own modern PHP implementation of this standard (and webauthn by the way).

**Comment by emlun** [comment]
Thank you for your contributions, and sorry this never went anywhere. Since the U2F API is now obsolete, we're archiving this repository and ceasing maintenance.

**Pull request closed without merging**
