### PR TITLE
Require phpunit5.7 and fix tests path in phpunit.xml

### PR DESCRIPTION
**Pull request by ChristophWurst**
Should fix https://github.com/Yubico/php-u2flib-server/pull/55#issuecomment-299795002, but let's see what Travis reports.

### CODE REVIEW

**Comment by ChristophWurst** [comment]
💥 as expected:
```
composer install

You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug

Loading composer repositories with package information

Updating dependencies (including require-dev)

Your requirements could not be resolved to an installable set of packages.

  Problem 1

    - phpunit/phpunit 5.7.9 requires php ^5.6 || ^7.0 -> your PHP version (5.3.29) does not satisfy that requirement.

    - phpunit/phpunit 5.7.8 requires php ^5.6 || ^7.0 -> your PHP version (5.3.29) does not satisfy that requirement.

    - phpunit/phpunit 5.7.7 requires php ^5.6 || ^7.0 -> your PHP version (5.3.29) does not satisfy that requirement.

    - phpunit/phpunit 5.7.6 requires php ^5.6 || ^7.0 -> your PHP version (5.3.29) does not satisfy that requirement.

    - phpunit/phpunit 5.7.5 requires php ^5.6 || ^7.0 -> your PHP version (5.3.29) does not satisfy that requirement.

    - phpunit/phpunit 5.7.4 requires php ^5.6 || ^7.0 -> your PHP version (5.3.29) does not satisfy that requirement.

    - phpunit/phpunit 5.7.3 requires php ^5.6 || ^7.0 -> your PHP version (5.3.29) does not satisfy that requirement.

    - phpunit/phpunit 5.7.2 requires php ^5.6 || ^7.0 -> your PHP version (5.3.29) does not satisfy that requirement.

    - phpunit/phpunit 5.7.19 requires php ^5.6 || ^7.0 -> your PHP version (5.3.29) does not satisfy that requirement.

    - phpunit/phpunit 5.7.18 requires php ^5.6 || ^7.0 -> your PHP version (5.3.29) does not satisfy that requirement.

    - phpunit/phpunit 5.7.17 requires php ^5.6 || ^7.0 -> your PHP version (5.3.29) does not satisfy that requirement.

    - phpunit/phpunit 5.7.16 requires php ^5.6 || ^7.0 -> your PHP version (5.3.29) does not satisfy that requirement.

    - phpunit/phpunit 5.7.15 requires php ^5.6 || ^7.0 -> your PHP version (5.3.29) does not satisfy that requirement.

    - phpunit/phpunit 5.7.14 requires php ^5.6 || ^7.0 -> your PHP version (5.3.29) does not satisfy that requirement.

    - phpunit/phpunit 5.7.13 requires php ^5.6 || ^7.0 -> your PHP version (5.3.29) does not satisfy that requirement.

    - phpunit/phpunit 5.7.12 requires php ^5.6 || ^7.0 -> your PHP version (5.3.29) does not satisfy that requirement.

    - phpunit/phpunit 5.7.11 requires php ^5.6 || ^7.0 -> your PHP version (5.3.29) does not satisfy that requirement.

    - phpunit/phpunit 5.7.10 requires php ^5.6 || ^7.0 -> your PHP version (5.3.29) does not satisfy that requirement.

    - phpunit/phpunit 5.7.1 requires php ^5.6 || ^7.0 -> your PHP version (5.3.29) does not satisfy that requirement.

    - phpunit/phpunit 5.7.0 requires php ^5.6 || ^7.0 -> your PHP version (5.3.29) does not satisfy that requirement.

    - Installation request for phpunit/phpunit ~5.7 -> satisfiable by phpunit/phpunit[5.7.0, 5.7.1, 5.7.10, 5.7.11, 5.7.12, 5.7.13, 5.7.14, 5.7.15, 5.7.16, 5.7.17, 5.7.18, 5.7.19, 5.7.2, 5.7.3, 5.7.4, 5.7.5, 5.7.6, 5.7.7, 5.7.8, 5.7.9].

The command "composer install" failed and exited with 2 during .
```

So, my question is: do you still want to support php 5.3, 5.4 and 5.5 in 2017? Of course there might be a solution to solve this CI error, but I'm wondering if that's worth the effort.

**Comment by ChristophWurst** [comment]
This resolves CI issues for php 5.6-7.0 though.

On a side note, I recommend adding php7.1 to the test matrix too ;-)

**Comment by klali** [comment]
I guess it's fine to drop anything before php 5.6 if it's a hassle.

I just pushed 08eeffd871d65400b3911027b17eec7a48ccb9a1 on a branch as a different way of resolving phpunit 5/6 incompatibilities, I'm not sure which way is best or considered cleanest. Thoughts?

**Comment by ChristophWurst** [comment]
> I guess it's fine to drop anything before php 5.6 if it's a hassle.

Great! I've changed the Travis config accordingly. To ensure nobody tries to require this lib via composer on php<=5.5, I've also added the platform dependency to the composer file.

> I just pushed 08eeffd on a branch as a different way of resolving phpunit 5/6 incompatibilities, I'm not sure which way is best or considered cleanest. Thoughts?

Well, although your approach could temporarily fix the CI failures, it looks error-prone IMO. For example the newer version of phpunit could internally require another class that can't be resolved. Loading it via composer is the cleaner solution I think. However, I'll leave this consideration up to the maintainers of this lib 😉 

If I may suggest, it could be helpful to enable Travis' beta feature *nightly builds*. Those would have detected the CI errors earlier, when the phpunit version changed.

**Comment by LukasReschke** [comment]
Personally, I'd be fine with both :-)

**Comment by ChristophWurst** [comment]
So how do we proceed here? 🎲? 😉

**Comment by klali** [comment]
I'm fine with your approach. Thanks for contributing, merging.

**Pull request merged**
