### PR TITLE
Use common challenge for multiple registrations

### PR DESCRIPTION
**Pull request by zauguin**
With U2F API v1.1 the same challenge is used for all registrations, so with this it is easier to use this library with the new API.

### CODE REVIEW

**Comment by ChristophWurst** [comment]
cc @klali @LukasReschke as potential reviewers :-)

**Comment by ChristophWurst** [comment]
Travis CI error seems unrelated. It fails only on php7, looks like a different version of phpunit is installed there which is incompatible with the current tests (they are using namespaced classes now) https://travis-ci.org/Yubico/php-u2flib-server/jobs/229318480

**Comment by ChristophWurst** [comment]
> Travis CI error seems unrelated. It fails only on php7, looks like a different version of phpunit is installed there which is incompatible with the current tests (they are using namespaced classes now) https://travis-ci.org/Yubico/php-u2flib-server/jobs/229318480

I will take a look at this.

**Comment by klali** [comment]
This looks good to me, planning to merge it but I'd like to land the phpunit fixes in #56 first.

**Comment by ChristophWurst** [comment]
Hey @klali,

thanks a lot for your quick response and for merging those PRs! Will those changes automatically be published to the composer registry?

**Comment by ChristophWurst** [comment]
I see the `dev-master` is already available: https://packagist.org/packages/yubico/u2flib-server#dev-master

**Comment by klali** [comment]
yeah.. I guess we (I) should make a 1.0.1 release with the last couple of fixes. Would you be helped by a tagged release?

**Comment by ChristophWurst** [comment]
Yes, that would be great

**Comment by klali** [comment]
1.0.1 is pushed

**Comment by ChristophWurst** [comment]
Thanks a lot! I'm already using it [here](https://github.com/nextcloud/twofactor_u2f/pull/49) 🚀

**Pull request merged**
