### PR TITLE
Type safety, CSPRNG, avoid chr()

### PR DESCRIPTION
**Pull request by paragonie-scott**
https://paragonie.com/blog/2017/02/cryptographically-secure-php-development#chr

### CODE REVIEW

**Comment by MKodde** [comment]
Question to the maintainers: This change will break compatibility with older PHP versions `< 7.0` I'm not up to speed with the development guidelines when version compatibility is concerned. Is this something to consider here, or at least to mention in the upcoming release :)

**Comment by MKodde** [comment]
Yep, that was me :smile: After writing that comment I realized the random_compat polyfill was also added to the project.

**Comment by klali** [comment]
Thanks for poking me.

I would say that the U2F libraries currently existing is in a sort of maintainance mode with webauthn happening. With that said we should be clearer on that and communicating what we consider should be happening with them.

As for this pull request I'm fine with most of it. How important do you consider the switch from openssl_random_pseudo_bytes() ? I'd like to avoid adding more dependencies if we don't have to.

**Comment by paragonie-scott** [comment]
> I would say that the U2F libraries currently existing is in a sort of maintainance mode with webauthn happening.

[Funny that you should mention that...](https://paragonie.com/blog/2018/08/security-concerns-surrounding-webauthn-don-t-implement-ecdaa-yet)

> How important do you consider the switch from openssl_random_pseudo_bytes() ?

OpenSSL's userspace PRNG has [caused collisions in PHP software](https://github.com/ramsey/uuid/issues/80) before. Your users are much better served by the kernel's CSPRNG, which is what random_compat uses (and what PHP 7+ does, natively).

**Comment by klali** [comment]
Agreed the points you make there, yet webauthn seems to be happening in the browsers which is the framework we have to work in here.

Fair enough on prng, going to merge this. Thank you!

**Comment by klali** [comment]
So the psalm checks seem to fail now that this is merged (https://travis-ci.org/Yubico/php-u2flib-server/jobs/419535637) but worked on the pull-request, do you have an inkling as to what's going on here?

**Pull request merged**
